cc_test (
    name = '249_test',
    srcs = '249_test.cc',
)

cc_test (
    name = '54_test',
    srcs = '54_test.cc',
)

cc_test (
    name = '363_test',
    srcs = '363_test.cc',
)

cc_test (
    name = '167_test',
    srcs = '167_test.cc',
)
